version: "3.9"
services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "macbook"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: weather
    container_name: weather-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev

      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: "postgres"
      DB_USER: "macbook"
      DB_PASSWORD: "postgres"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge