database:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

hibernate:
    dialect: ord.hibernate.dialect.PostgreSQLDialect
    show_sql: true